/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.qing.logiclayer;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class QueryOpenWebPageByDocidResponse implements org.apache.thrift.TBase<QueryOpenWebPageByDocidResponse, QueryOpenWebPageByDocidResponse._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("QueryOpenWebPageByDocidResponse");

  private static final org.apache.thrift.protocol.TField LOGID_FIELD_DESC = new org.apache.thrift.protocol.TField("logid", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField WEBPAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("webpage", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new QueryOpenWebPageByDocidResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new QueryOpenWebPageByDocidResponseTupleSchemeFactory());
  }

  public long logid; // required
  public OpenWebPageContent webpage; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LOGID((short)1, "logid"),
    WEBPAGE((short)2, "webpage");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LOGID
          return LOGID;
        case 2: // WEBPAGE
          return WEBPAGE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __LOGID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LOGID, new org.apache.thrift.meta_data.FieldMetaData("logid", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.WEBPAGE, new org.apache.thrift.meta_data.FieldMetaData("webpage", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, OpenWebPageContent.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(QueryOpenWebPageByDocidResponse.class, metaDataMap);
  }

  public QueryOpenWebPageByDocidResponse() {
    this.logid = 1001L;

  }

  public QueryOpenWebPageByDocidResponse(
    long logid,
    OpenWebPageContent webpage)
  {
    this();
    this.logid = logid;
    setLogidIsSet(true);
    this.webpage = webpage;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public QueryOpenWebPageByDocidResponse(QueryOpenWebPageByDocidResponse other) {
    __isset_bitfield = other.__isset_bitfield;
    this.logid = other.logid;
    if (other.isSetWebpage()) {
      this.webpage = new OpenWebPageContent(other.webpage);
    }
  }

  public QueryOpenWebPageByDocidResponse deepCopy() {
    return new QueryOpenWebPageByDocidResponse(this);
  }

  @Override
  public void clear() {
    this.logid = 1001L;

    this.webpage = null;
  }

  public long getLogid() {
    return this.logid;
  }

  public QueryOpenWebPageByDocidResponse setLogid(long logid) {
    this.logid = logid;
    setLogidIsSet(true);
    return this;
  }

  public void unsetLogid() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __LOGID_ISSET_ID);
  }

  /** Returns true if field logid is set (has been assigned a value) and false otherwise */
  public boolean isSetLogid() {
    return EncodingUtils.testBit(__isset_bitfield, __LOGID_ISSET_ID);
  }

  public void setLogidIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __LOGID_ISSET_ID, value);
  }

  public OpenWebPageContent getWebpage() {
    return this.webpage;
  }

  public QueryOpenWebPageByDocidResponse setWebpage(OpenWebPageContent webpage) {
    this.webpage = webpage;
    return this;
  }

  public void unsetWebpage() {
    this.webpage = null;
  }

  /** Returns true if field webpage is set (has been assigned a value) and false otherwise */
  public boolean isSetWebpage() {
    return this.webpage != null;
  }

  public void setWebpageIsSet(boolean value) {
    if (!value) {
      this.webpage = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case LOGID:
      if (value == null) {
        unsetLogid();
      } else {
        setLogid((Long)value);
      }
      break;

    case WEBPAGE:
      if (value == null) {
        unsetWebpage();
      } else {
        setWebpage((OpenWebPageContent)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case LOGID:
      return Long.valueOf(getLogid());

    case WEBPAGE:
      return getWebpage();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case LOGID:
      return isSetLogid();
    case WEBPAGE:
      return isSetWebpage();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof QueryOpenWebPageByDocidResponse)
      return this.equals((QueryOpenWebPageByDocidResponse)that);
    return false;
  }

  public boolean equals(QueryOpenWebPageByDocidResponse that) {
    if (that == null)
      return false;

    boolean this_present_logid = true;
    boolean that_present_logid = true;
    if (this_present_logid || that_present_logid) {
      if (!(this_present_logid && that_present_logid))
        return false;
      if (this.logid != that.logid)
        return false;
    }

    boolean this_present_webpage = true && this.isSetWebpage();
    boolean that_present_webpage = true && that.isSetWebpage();
    if (this_present_webpage || that_present_webpage) {
      if (!(this_present_webpage && that_present_webpage))
        return false;
      if (!this.webpage.equals(that.webpage))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(QueryOpenWebPageByDocidResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    QueryOpenWebPageByDocidResponse typedOther = (QueryOpenWebPageByDocidResponse)other;

    lastComparison = Boolean.valueOf(isSetLogid()).compareTo(typedOther.isSetLogid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLogid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.logid, typedOther.logid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetWebpage()).compareTo(typedOther.isSetWebpage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWebpage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.webpage, typedOther.webpage);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("QueryOpenWebPageByDocidResponse(");
    boolean first = true;

    sb.append("logid:");
    sb.append(this.logid);
    first = false;
    if (!first) sb.append(", ");
    sb.append("webpage:");
    if (this.webpage == null) {
      sb.append("null");
    } else {
      sb.append(this.webpage);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'logid' because it's a primitive and you chose the non-beans generator.
    if (webpage == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'webpage' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (webpage != null) {
      webpage.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class QueryOpenWebPageByDocidResponseStandardSchemeFactory implements SchemeFactory {
    public QueryOpenWebPageByDocidResponseStandardScheme getScheme() {
      return new QueryOpenWebPageByDocidResponseStandardScheme();
    }
  }

  private static class QueryOpenWebPageByDocidResponseStandardScheme extends StandardScheme<QueryOpenWebPageByDocidResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, QueryOpenWebPageByDocidResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LOGID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.logid = iprot.readI64();
              struct.setLogidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // WEBPAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.webpage = new OpenWebPageContent();
              struct.webpage.read(iprot);
              struct.setWebpageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetLogid()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'logid' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, QueryOpenWebPageByDocidResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(LOGID_FIELD_DESC);
      oprot.writeI64(struct.logid);
      oprot.writeFieldEnd();
      if (struct.webpage != null) {
        oprot.writeFieldBegin(WEBPAGE_FIELD_DESC);
        struct.webpage.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class QueryOpenWebPageByDocidResponseTupleSchemeFactory implements SchemeFactory {
    public QueryOpenWebPageByDocidResponseTupleScheme getScheme() {
      return new QueryOpenWebPageByDocidResponseTupleScheme();
    }
  }

  private static class QueryOpenWebPageByDocidResponseTupleScheme extends TupleScheme<QueryOpenWebPageByDocidResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, QueryOpenWebPageByDocidResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI64(struct.logid);
      struct.webpage.write(oprot);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, QueryOpenWebPageByDocidResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.logid = iprot.readI64();
      struct.setLogidIsSet(true);
      struct.webpage = new OpenWebPageContent();
      struct.webpage.read(iprot);
      struct.setWebpageIsSet(true);
    }
  }

}

