/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.lighting.rpc.webmetaserver.model;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum WMSTaskStatus implements org.apache.thrift.TEnum {
  WMS_WEBSITE_TASK_STATUS_NOTHING(0),
  WMS_WEBSITE_TASK_STATUS_SUCCESS(1);

  private final int value;

  private WMSTaskStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static WMSTaskStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return WMS_WEBSITE_TASK_STATUS_NOTHING;
      case 1:
        return WMS_WEBSITE_TASK_STATUS_SUCCESS;
      default:
        return null;
    }
  }
}
