/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.lighting.rpc.webmetaserver.model;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum WMSWebsiteUrlRuleType implements org.apache.thrift.TEnum {
  WMS_WEBSITE_URL_RULE_HIT(0);

  private final int value;

  private WMSWebsiteUrlRuleType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static WMSWebsiteUrlRuleType findByValue(int value) { 
    switch (value) {
      case 0:
        return WMS_WEBSITE_URL_RULE_HIT;
      default:
        return null;
    }
  }
}
