/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.qing.logiclayer;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class QueryHotWebPageByEventRequest implements org.apache.thrift.TBase<QueryHotWebPageByEventRequest, QueryHotWebPageByEventRequest._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("QueryHotWebPageByEventRequest");

  private static final org.apache.thrift.protocol.TField LANGUGE_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("langugeType", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField EVENTID_FIELD_DESC = new org.apache.thrift.protocol.TField("eventid", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField PAGENO_FIELD_DESC = new org.apache.thrift.protocol.TField("pageno", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField PAGESIZE_FIELD_DESC = new org.apache.thrift.protocol.TField("pagesize", org.apache.thrift.protocol.TType.I32, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new QueryHotWebPageByEventRequestStandardSchemeFactory());
    schemes.put(TupleScheme.class, new QueryHotWebPageByEventRequestTupleSchemeFactory());
  }

  /**
   * 
   * @see OpenCommonLanguge
   */
  public OpenCommonLanguge langugeType; // required
  public String eventid; // required
  public int pageno; // required
  public int pagesize; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see OpenCommonLanguge
     */
    LANGUGE_TYPE((short)1, "langugeType"),
    EVENTID((short)2, "eventid"),
    PAGENO((short)3, "pageno"),
    PAGESIZE((short)4, "pagesize");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LANGUGE_TYPE
          return LANGUGE_TYPE;
        case 2: // EVENTID
          return EVENTID;
        case 3: // PAGENO
          return PAGENO;
        case 4: // PAGESIZE
          return PAGESIZE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PAGENO_ISSET_ID = 0;
  private static final int __PAGESIZE_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LANGUGE_TYPE, new org.apache.thrift.meta_data.FieldMetaData("langugeType", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, OpenCommonLanguge.class)));
    tmpMap.put(_Fields.EVENTID, new org.apache.thrift.meta_data.FieldMetaData("eventid", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PAGENO, new org.apache.thrift.meta_data.FieldMetaData("pageno", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.PAGESIZE, new org.apache.thrift.meta_data.FieldMetaData("pagesize", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(QueryHotWebPageByEventRequest.class, metaDataMap);
  }

  public QueryHotWebPageByEventRequest() {
    this.langugeType = com.qing.logiclayer.OpenCommonLanguge.OC_LAN_CHINESE_ZH_CN;

    this.pageno = 0;

    this.pagesize = 10;

  }

  public QueryHotWebPageByEventRequest(
    OpenCommonLanguge langugeType,
    String eventid,
    int pageno,
    int pagesize)
  {
    this();
    this.langugeType = langugeType;
    this.eventid = eventid;
    this.pageno = pageno;
    setPagenoIsSet(true);
    this.pagesize = pagesize;
    setPagesizeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public QueryHotWebPageByEventRequest(QueryHotWebPageByEventRequest other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetLangugeType()) {
      this.langugeType = other.langugeType;
    }
    if (other.isSetEventid()) {
      this.eventid = other.eventid;
    }
    this.pageno = other.pageno;
    this.pagesize = other.pagesize;
  }

  public QueryHotWebPageByEventRequest deepCopy() {
    return new QueryHotWebPageByEventRequest(this);
  }

  @Override
  public void clear() {
    this.langugeType = com.qing.logiclayer.OpenCommonLanguge.OC_LAN_CHINESE_ZH_CN;

    this.eventid = null;
    this.pageno = 0;

    this.pagesize = 10;

  }

  /**
   * 
   * @see OpenCommonLanguge
   */
  public OpenCommonLanguge getLangugeType() {
    return this.langugeType;
  }

  /**
   * 
   * @see OpenCommonLanguge
   */
  public QueryHotWebPageByEventRequest setLangugeType(OpenCommonLanguge langugeType) {
    this.langugeType = langugeType;
    return this;
  }

  public void unsetLangugeType() {
    this.langugeType = null;
  }

  /** Returns true if field langugeType is set (has been assigned a value) and false otherwise */
  public boolean isSetLangugeType() {
    return this.langugeType != null;
  }

  public void setLangugeTypeIsSet(boolean value) {
    if (!value) {
      this.langugeType = null;
    }
  }

  public String getEventid() {
    return this.eventid;
  }

  public QueryHotWebPageByEventRequest setEventid(String eventid) {
    this.eventid = eventid;
    return this;
  }

  public void unsetEventid() {
    this.eventid = null;
  }

  /** Returns true if field eventid is set (has been assigned a value) and false otherwise */
  public boolean isSetEventid() {
    return this.eventid != null;
  }

  public void setEventidIsSet(boolean value) {
    if (!value) {
      this.eventid = null;
    }
  }

  public int getPageno() {
    return this.pageno;
  }

  public QueryHotWebPageByEventRequest setPageno(int pageno) {
    this.pageno = pageno;
    setPagenoIsSet(true);
    return this;
  }

  public void unsetPageno() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PAGENO_ISSET_ID);
  }

  /** Returns true if field pageno is set (has been assigned a value) and false otherwise */
  public boolean isSetPageno() {
    return EncodingUtils.testBit(__isset_bitfield, __PAGENO_ISSET_ID);
  }

  public void setPagenoIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PAGENO_ISSET_ID, value);
  }

  public int getPagesize() {
    return this.pagesize;
  }

  public QueryHotWebPageByEventRequest setPagesize(int pagesize) {
    this.pagesize = pagesize;
    setPagesizeIsSet(true);
    return this;
  }

  public void unsetPagesize() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PAGESIZE_ISSET_ID);
  }

  /** Returns true if field pagesize is set (has been assigned a value) and false otherwise */
  public boolean isSetPagesize() {
    return EncodingUtils.testBit(__isset_bitfield, __PAGESIZE_ISSET_ID);
  }

  public void setPagesizeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PAGESIZE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case LANGUGE_TYPE:
      if (value == null) {
        unsetLangugeType();
      } else {
        setLangugeType((OpenCommonLanguge)value);
      }
      break;

    case EVENTID:
      if (value == null) {
        unsetEventid();
      } else {
        setEventid((String)value);
      }
      break;

    case PAGENO:
      if (value == null) {
        unsetPageno();
      } else {
        setPageno((Integer)value);
      }
      break;

    case PAGESIZE:
      if (value == null) {
        unsetPagesize();
      } else {
        setPagesize((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case LANGUGE_TYPE:
      return getLangugeType();

    case EVENTID:
      return getEventid();

    case PAGENO:
      return Integer.valueOf(getPageno());

    case PAGESIZE:
      return Integer.valueOf(getPagesize());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case LANGUGE_TYPE:
      return isSetLangugeType();
    case EVENTID:
      return isSetEventid();
    case PAGENO:
      return isSetPageno();
    case PAGESIZE:
      return isSetPagesize();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof QueryHotWebPageByEventRequest)
      return this.equals((QueryHotWebPageByEventRequest)that);
    return false;
  }

  public boolean equals(QueryHotWebPageByEventRequest that) {
    if (that == null)
      return false;

    boolean this_present_langugeType = true && this.isSetLangugeType();
    boolean that_present_langugeType = true && that.isSetLangugeType();
    if (this_present_langugeType || that_present_langugeType) {
      if (!(this_present_langugeType && that_present_langugeType))
        return false;
      if (!this.langugeType.equals(that.langugeType))
        return false;
    }

    boolean this_present_eventid = true && this.isSetEventid();
    boolean that_present_eventid = true && that.isSetEventid();
    if (this_present_eventid || that_present_eventid) {
      if (!(this_present_eventid && that_present_eventid))
        return false;
      if (!this.eventid.equals(that.eventid))
        return false;
    }

    boolean this_present_pageno = true;
    boolean that_present_pageno = true;
    if (this_present_pageno || that_present_pageno) {
      if (!(this_present_pageno && that_present_pageno))
        return false;
      if (this.pageno != that.pageno)
        return false;
    }

    boolean this_present_pagesize = true;
    boolean that_present_pagesize = true;
    if (this_present_pagesize || that_present_pagesize) {
      if (!(this_present_pagesize && that_present_pagesize))
        return false;
      if (this.pagesize != that.pagesize)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(QueryHotWebPageByEventRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    QueryHotWebPageByEventRequest typedOther = (QueryHotWebPageByEventRequest)other;

    lastComparison = Boolean.valueOf(isSetLangugeType()).compareTo(typedOther.isSetLangugeType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLangugeType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.langugeType, typedOther.langugeType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEventid()).compareTo(typedOther.isSetEventid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEventid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.eventid, typedOther.eventid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPageno()).compareTo(typedOther.isSetPageno());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPageno()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pageno, typedOther.pageno);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPagesize()).compareTo(typedOther.isSetPagesize());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPagesize()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pagesize, typedOther.pagesize);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("QueryHotWebPageByEventRequest(");
    boolean first = true;

    sb.append("langugeType:");
    if (this.langugeType == null) {
      sb.append("null");
    } else {
      sb.append(this.langugeType);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("eventid:");
    if (this.eventid == null) {
      sb.append("null");
    } else {
      sb.append(this.eventid);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("pageno:");
    sb.append(this.pageno);
    first = false;
    if (!first) sb.append(", ");
    sb.append("pagesize:");
    sb.append(this.pagesize);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (langugeType == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'langugeType' was not present! Struct: " + toString());
    }
    if (eventid == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'eventid' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'pageno' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'pagesize' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class QueryHotWebPageByEventRequestStandardSchemeFactory implements SchemeFactory {
    public QueryHotWebPageByEventRequestStandardScheme getScheme() {
      return new QueryHotWebPageByEventRequestStandardScheme();
    }
  }

  private static class QueryHotWebPageByEventRequestStandardScheme extends StandardScheme<QueryHotWebPageByEventRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, QueryHotWebPageByEventRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LANGUGE_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.langugeType = OpenCommonLanguge.findByValue(iprot.readI32());
              struct.setLangugeTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // EVENTID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.eventid = iprot.readString();
              struct.setEventidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PAGENO
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.pageno = iprot.readI32();
              struct.setPagenoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // PAGESIZE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.pagesize = iprot.readI32();
              struct.setPagesizeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetPageno()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'pageno' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetPagesize()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'pagesize' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, QueryHotWebPageByEventRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.langugeType != null) {
        oprot.writeFieldBegin(LANGUGE_TYPE_FIELD_DESC);
        oprot.writeI32(struct.langugeType.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.eventid != null) {
        oprot.writeFieldBegin(EVENTID_FIELD_DESC);
        oprot.writeString(struct.eventid);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(PAGENO_FIELD_DESC);
      oprot.writeI32(struct.pageno);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(PAGESIZE_FIELD_DESC);
      oprot.writeI32(struct.pagesize);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class QueryHotWebPageByEventRequestTupleSchemeFactory implements SchemeFactory {
    public QueryHotWebPageByEventRequestTupleScheme getScheme() {
      return new QueryHotWebPageByEventRequestTupleScheme();
    }
  }

  private static class QueryHotWebPageByEventRequestTupleScheme extends TupleScheme<QueryHotWebPageByEventRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, QueryHotWebPageByEventRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.langugeType.getValue());
      oprot.writeString(struct.eventid);
      oprot.writeI32(struct.pageno);
      oprot.writeI32(struct.pagesize);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, QueryHotWebPageByEventRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.langugeType = OpenCommonLanguge.findByValue(iprot.readI32());
      struct.setLangugeTypeIsSet(true);
      struct.eventid = iprot.readString();
      struct.setEventidIsSet(true);
      struct.pageno = iprot.readI32();
      struct.setPagenoIsSet(true);
      struct.pagesize = iprot.readI32();
      struct.setPagesizeIsSet(true);
    }
  }

}

