/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.qing.logiclayer;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TimeTrendSet implements org.apache.thrift.TBase<TimeTrendSet, TimeTrendSet._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TimeTrendSet");

  private static final org.apache.thrift.protocol.TField DATE_FIELD_DESC = new org.apache.thrift.protocol.TField("date", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField WORDINFOS_FIELD_DESC = new org.apache.thrift.protocol.TField("wordinfos", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TimeTrendSetStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TimeTrendSetTupleSchemeFactory());
  }

  public String date; // required
  public List<WordInfo> wordinfos; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DATE((short)1, "date"),
    WORDINFOS((short)2, "wordinfos");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DATE
          return DATE;
        case 2: // WORDINFOS
          return WORDINFOS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DATE, new org.apache.thrift.meta_data.FieldMetaData("date", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.WORDINFOS, new org.apache.thrift.meta_data.FieldMetaData("wordinfos", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, WordInfo.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TimeTrendSet.class, metaDataMap);
  }

  public TimeTrendSet() {
  }

  public TimeTrendSet(
    String date,
    List<WordInfo> wordinfos)
  {
    this();
    this.date = date;
    this.wordinfos = wordinfos;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TimeTrendSet(TimeTrendSet other) {
    if (other.isSetDate()) {
      this.date = other.date;
    }
    if (other.isSetWordinfos()) {
      List<WordInfo> __this__wordinfos = new ArrayList<WordInfo>();
      for (WordInfo other_element : other.wordinfos) {
        __this__wordinfos.add(new WordInfo(other_element));
      }
      this.wordinfos = __this__wordinfos;
    }
  }

  public TimeTrendSet deepCopy() {
    return new TimeTrendSet(this);
  }

  @Override
  public void clear() {
    this.date = null;
    this.wordinfos = null;
  }

  public String getDate() {
    return this.date;
  }

  public TimeTrendSet setDate(String date) {
    this.date = date;
    return this;
  }

  public void unsetDate() {
    this.date = null;
  }

  /** Returns true if field date is set (has been assigned a value) and false otherwise */
  public boolean isSetDate() {
    return this.date != null;
  }

  public void setDateIsSet(boolean value) {
    if (!value) {
      this.date = null;
    }
  }

  public int getWordinfosSize() {
    return (this.wordinfos == null) ? 0 : this.wordinfos.size();
  }

  public java.util.Iterator<WordInfo> getWordinfosIterator() {
    return (this.wordinfos == null) ? null : this.wordinfos.iterator();
  }

  public void addToWordinfos(WordInfo elem) {
    if (this.wordinfos == null) {
      this.wordinfos = new ArrayList<WordInfo>();
    }
    this.wordinfos.add(elem);
  }

  public List<WordInfo> getWordinfos() {
    return this.wordinfos;
  }

  public TimeTrendSet setWordinfos(List<WordInfo> wordinfos) {
    this.wordinfos = wordinfos;
    return this;
  }

  public void unsetWordinfos() {
    this.wordinfos = null;
  }

  /** Returns true if field wordinfos is set (has been assigned a value) and false otherwise */
  public boolean isSetWordinfos() {
    return this.wordinfos != null;
  }

  public void setWordinfosIsSet(boolean value) {
    if (!value) {
      this.wordinfos = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case DATE:
      if (value == null) {
        unsetDate();
      } else {
        setDate((String)value);
      }
      break;

    case WORDINFOS:
      if (value == null) {
        unsetWordinfos();
      } else {
        setWordinfos((List<WordInfo>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case DATE:
      return getDate();

    case WORDINFOS:
      return getWordinfos();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case DATE:
      return isSetDate();
    case WORDINFOS:
      return isSetWordinfos();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TimeTrendSet)
      return this.equals((TimeTrendSet)that);
    return false;
  }

  public boolean equals(TimeTrendSet that) {
    if (that == null)
      return false;

    boolean this_present_date = true && this.isSetDate();
    boolean that_present_date = true && that.isSetDate();
    if (this_present_date || that_present_date) {
      if (!(this_present_date && that_present_date))
        return false;
      if (!this.date.equals(that.date))
        return false;
    }

    boolean this_present_wordinfos = true && this.isSetWordinfos();
    boolean that_present_wordinfos = true && that.isSetWordinfos();
    if (this_present_wordinfos || that_present_wordinfos) {
      if (!(this_present_wordinfos && that_present_wordinfos))
        return false;
      if (!this.wordinfos.equals(that.wordinfos))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(TimeTrendSet other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    TimeTrendSet typedOther = (TimeTrendSet)other;

    lastComparison = Boolean.valueOf(isSetDate()).compareTo(typedOther.isSetDate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.date, typedOther.date);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetWordinfos()).compareTo(typedOther.isSetWordinfos());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWordinfos()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.wordinfos, typedOther.wordinfos);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TimeTrendSet(");
    boolean first = true;

    sb.append("date:");
    if (this.date == null) {
      sb.append("null");
    } else {
      sb.append(this.date);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("wordinfos:");
    if (this.wordinfos == null) {
      sb.append("null");
    } else {
      sb.append(this.wordinfos);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TimeTrendSetStandardSchemeFactory implements SchemeFactory {
    public TimeTrendSetStandardScheme getScheme() {
      return new TimeTrendSetStandardScheme();
    }
  }

  private static class TimeTrendSetStandardScheme extends StandardScheme<TimeTrendSet> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TimeTrendSet struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DATE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.date = iprot.readString();
              struct.setDateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // WORDINFOS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.wordinfos = new ArrayList<WordInfo>(_list0.size);
                for (int _i1 = 0; _i1 < _list0.size; ++_i1)
                {
                  WordInfo _elem2; // required
                  _elem2 = new WordInfo();
                  _elem2.read(iprot);
                  struct.wordinfos.add(_elem2);
                }
                iprot.readListEnd();
              }
              struct.setWordinfosIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TimeTrendSet struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.date != null) {
        oprot.writeFieldBegin(DATE_FIELD_DESC);
        oprot.writeString(struct.date);
        oprot.writeFieldEnd();
      }
      if (struct.wordinfos != null) {
        oprot.writeFieldBegin(WORDINFOS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.wordinfos.size()));
          for (WordInfo _iter3 : struct.wordinfos)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TimeTrendSetTupleSchemeFactory implements SchemeFactory {
    public TimeTrendSetTupleScheme getScheme() {
      return new TimeTrendSetTupleScheme();
    }
  }

  private static class TimeTrendSetTupleScheme extends TupleScheme<TimeTrendSet> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TimeTrendSet struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetDate()) {
        optionals.set(0);
      }
      if (struct.isSetWordinfos()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetDate()) {
        oprot.writeString(struct.date);
      }
      if (struct.isSetWordinfos()) {
        {
          oprot.writeI32(struct.wordinfos.size());
          for (WordInfo _iter4 : struct.wordinfos)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TimeTrendSet struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.date = iprot.readString();
        struct.setDateIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.wordinfos = new ArrayList<WordInfo>(_list5.size);
          for (int _i6 = 0; _i6 < _list5.size; ++_i6)
          {
            WordInfo _elem7; // required
            _elem7 = new WordInfo();
            _elem7.read(iprot);
            struct.wordinfos.add(_elem7);
          }
        }
        struct.setWordinfosIsSet(true);
      }
    }
  }

}

